name: JetBrains Runtime Setup
description: Setup JetBrains Runtime 17
runs:
  using: composite
  steps:
    - name: Install and Setup JetBrains Runtime (Linux / Windows)
      shell: bash
      if: runner.os != 'macOS'
      env:
        JBR_URL_Linux_X64: 'https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-17.0.9-linux-x64-b1000.46.tar.gz'
        JBR_URL_Windows_X64: 'https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-17.0.9-windows-x64-b1000.46.tar.gz'
      run: |
        mkdir -p "$HOME/.jdks/jbr17"
        wget -q -O - "$JBR_URL_${{ runner.os }}_${{ runner.arch }}" | tar -xzf - --strip-components=1 -C "$HOME/.jdks/jbr17"
        echo "JAVA_HOME=$HOME/.jdks/jbr17" >> $GITHUB_ENV

    - name: Install and Setup JetBrains Runtime (macOS)
      shell: bash
      if: runner.os == 'macOS'
      env:
        JBR_URL_macOS_X64: 'https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-17.0.9-osx-x64-b1000.46.tar.gz'
        JBR_URL_macOS_ARM64: 'https://cache-redirector.jetbrains.com/intellij-jbr/jbr_jcef-17.0.9-osx-aarch64-b1000.46.tar.gz'
      run: |
        mkdir -p "$HOME/.jdks/jbr17"
        wget -q -O - "$JBR_URL_${{ runner.os }}_${{ runner.arch }}" | tar -xzf - --strip-components=1 -C "$HOME/.jdks/jbr17"
        echo "JAVA_HOME=$HOME/.jdks/jbr17/Contents/Home" >> $GITHUB_ENV

    - name: Setup PATH
      shell: bash
      run: echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

    - name: Verify Java Setup
      shell: bash
      run: |
        java --version
        which java